# Generated by Django 4.0.4 on 2022-04-21 02:08

from django.db import migrations, models
import social.validators


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/post_videos', validators=[social.validators.file_size]),
        ),
    ]
