# Generated by Django 4.0.4 on 2022-05-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_comment_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
    ]
