# Generated by Django 4.0.4 on 2022-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0010_comment_content_type_comment_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=False, unique=True),
        ),
    ]
