# Generated by Django 4.0.4 on 2022-05-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0011_post_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="slug",),
    ]
