# Generated by Django 4.0.4 on 2022-05-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
    ]
