# Generated by Django 3.2.13 on 2022-05-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20220519_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttest',
            name='slugtest',
            field=models.SlugField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='posttest',
            name='bodytest',
            field=models.TextField(max_length=1000),
        ),
    ]
