# Generated by Django 3.2.13 on 2022-06-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0022_rename_slugtest_posttest_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=None, unique=True),
        ),
    ]
