# Generated by Django 3.2.13 on 2022-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0023_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
