# Generated by Django 4.0.4 on 2022-04-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pinterest_url',
        ),
    ]
