# Generated by Django 3.2.13 on 2022-12-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_bookcontent_bookorders_books_isbn_itema_itemb_itemc_itemd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookContent',
        ),
        migrations.RemoveField(
            model_name='isbn',
            name='books_ptr',
        ),
        migrations.DeleteModel(
            name='ItemA',
        ),
        migrations.DeleteModel(
            name='ItemB',
        ),
        migrations.DeleteModel(
            name='ItemC',
        ),
        migrations.DeleteModel(
            name='ItemD',
        ),
        migrations.DeleteModel(
            name='BookOrders',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='ISBN',
        ),
    ]
