# Generated by Django 4.0.4 on 2022-04-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
